import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CountriesProvider } from "./context/CountriesContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Nave from "./components/Nave";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen bg-white text-black relative">
          <CountriesProvider>
            <Nave />
            {children}
          </CountriesProvider>
        </div>
      </body>
    </html>
  );
}
